apiVersion: v1
kind: Pod
metadata:
  name: mongo-db-pod
  namespace: db-namespace
  labels:
    app: mongo-db
spec:
  containers:
    - name: mongo-container
      image: mongo
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_DATABASE
          value: StockDB
---
apiVersion: v1
kind: Service
metadata: 
  name: mongo-service
  namespace: db-namespace
spec: 
  selector: 
    app: mongo-db
  ports:
     - port: 27017
       protocol: TCP
       targetPort: 27017
  type: NodePort