kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-mongo
  labels:
    type: local
    app: mongo-db
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/mongo"
    type: Directory

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mongo
  namespace: $ENV
  labels:
    app: mongo-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

--- 

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db-statefulset
  namespace: $ENV
spec:
  serviceName: "mongo-service"
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: pvc-mongo
      containers:
        - name: mongo-container
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: StockDB
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db

---

apiVersion: v1
kind: Service
metadata: 
  name: mongo-service
  namespace: $ENV
spec: 
  selector: 
    app: mongo-db
  ports:
     - port: 27017
       protocol: TCP
       targetPort: 27017