apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: $ENV
  labels:
    app: user-app-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app-label
  template:
    metadata:
      labels:
        app: user-app-label
    spec:
      containers:
      - name: user-container
        image: monicashinde3/user-service-image:$BUILD_NUMBER
        ports:
        - name: user-port
          containerPort: 8300
        env:
          - name: MONGO_INITDB_HOST
            value: mongo-service.$ENV.svc.cluster.local
          - name: MONGO_INITDB_DATABASE
            value: StockDB
---
apiVersion: v1
kind: Service
metadata:
  name: user-app-service
  namespace: $ENV
spec:
  ports:
    - port: 8300
      nodePort: 31000
  selector:
    app: user-app-label
  type: NodePort