apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-deployment
  namespace: $ENV
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-app-label
  template:
    metadata:
      labels:
        app: stock-app-label
    spec:
      containers:
      - name: stock-container
        image: monicashinde3/stock-service-image:$BUILD_NUMBER
        ports:
        - name: stock-port
          containerPort: 8301
        env:
          - name: MONGO_INITDB_HOST
            value: mongo-service.$ENV.svc.cluster.local
          - name: MONGO_INITDB_DATABASE
            value: StockDB
          - name: USER_SERVICE_HOST
            value: user-app-service.$ENV.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: stock-app-service
  namespace: $ENV
spec:
  ports:
    - port: 8301
      nodePort: 31001
  selector:
    app: stock-app-label
  type: NodePort